import { readFile, writeFile } from "node:fs/promises";

const directory = new URL("../src/visionary/shaders/", import.meta.url);
const shaders = [
  ["preprocessShader", "preprocess"],
  ["gaussianShader", "gaussian"],
  ["radixSortShader", "radix_sort"],
];
let output = "// Generated by scripts/generate-shaders.mjs. Edit the WGSL sources instead.\n";
for (const [name, file] of shaders) {
  const source = await readFile(new URL(`${file}.wgsl`, directory), "utf8");
  output += `export const ${name} = ${JSON.stringify(source)};\n`;
}
await writeFile(new URL("generated.ts", directory), output);
